#!/usr/bin/env ruby

require 'socket'
require 'net/http'
require 'uri'

add_url = "http://localhost:4567/link/create"
post_url = URI.parse(add_url)
req = Net::HTTP::Post.new(post_url.path)
req.set_form_data({
  'url' => "http://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url",
  'msg' => ":blithe!~blithe@72.14.176.144 PRIVMSG #slurp-test :blah lol @ lol @ http://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url."
})
http = Net::HTTP.new(post_url.host, post_url.port)
res = http.start {|http| http.request(req) }
p res.body
